embedding:
  model_name: paraphrase-multilingual-MiniLM-L12-v2
  batch_size: 256
  n_jobs: 8

preprocessing:
  ignore_words:
    - APEX
    - CPT
    - Kunde
    - TBD
    - Nero
    # Add more words to ignore as needed

umap:
  enabled: true
  n_neighbors: 3
  min_dist: 0.0
  n_components: 3

hdbscan:
  min_cluster_size: 2
  min_samples: null
  cluster_selection_epsilon: 0.0

labeling:
  keywords: []
  yake_topk: 10
  yake_max_ngram: 3

output:
  top_n_clusters: 10
  include_noise: false
