embedding:
  model_name: paraphrase-multilingual-MiniLM-L12-v2
  batch_size: 256
  n_jobs: 8

umap:
  enabled: true
  n_neighbors: 15
  min_dist: 0.0
  n_components: 15

hdbscan:
  min_cluster_size: 25
  min_samples: null
  cluster_selection_epsilon: 0.0

labeling:
  keywords: ["PKI","SNC","APEX","SAP","GUI","Login","Anmeldung","Dashboard","Bug","Fehler"]
  yake_topk: 10
  yake_max_ngram: 3

output:
  top_n_clusters: 10
  include_noise: false
